services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge